---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/private/users":
    post:
      summary: Create new user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      created:
                        type: string
                    required:
                    - name
                    - email
                    - created
                required:
                - success
                - message
                - user
        '400':
          description: User did not pass validation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: object
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
