---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/private/internet_troubles":
    post:
      summary: Create new internet trouble
      tags:
      - InternetTrouble
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  internet_trouble:
                    type: object
                    properties:
                      id:
                        type: integer
                      trouble:
                        type: string
                      status:
                        type: string
                        nullable: true
                      category:
                        type: string
                        nullable: true
                      is_predicted:
                        type: boolean
                    required:
                    - id
                    - trouble
                    - is_predicted
                required:
                - success
                - message
                - internet_trouble
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: object
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trouble:
                  type: string
                category:
                  type: string
                status:
                  type: string
                is_predicted:
                  type: boolean
              required:
              - trouble
  "/api/v1/private/internet_troubles/{id}/edit":
    put:
      summary: Update created internet trouble
      tags:
      - InternetTrouble
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  internet_trouble:
                    type: object
                    properties:
                      trouble:
                        type: string
                        nullable: true
                      status:
                        type: string
                        nullable: true
                      category:
                        type: string
                        nullable: true
                      is_predicted:
                        type: boolean
                required:
                - success
                - message
                - internet_trouble
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: object
                required:
                - success
                - message
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trouble:
                  type: string
                category:
                  type: string
                status:
                  type: string
                is_predicted:
                  type: boolean
  "/api/v1/private/users":
    post:
      summary: Create new user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      created:
                        type: string
                    required:
                    - name
                    - email
                    - created
                required:
                - success
                - message
                - user
        '400':
          description: User did not pass validation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: object
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/api/v1/private/users/login":
    post:
      summary: Authenticate user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: Authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
                required:
                - success
                - message
                - token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/internet_troubles":
    post:
      summary: Internet Trouble
      tags:
      - InternetTrouble
      parameters: []
      responses:
        '200':
          description: Show Internet Trouble
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  internet_trouble:
                    type: object
                    properties:
                      id:
                        type: integer
                      trouble:
                        type: string
                      status:
                        type: string
                        nullable: true
                      category:
                        type: string
                        nullable: true
                      is_predicted:
                        type: boolean
                    required:
                    - id
                    - trouble
                    - is_predicted
                required:
                - success
                - message
                - internet_trouble
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                trouble_id:
                  type: int
              required:
              - email
              - trouble_id
securityDefinitions:
  Bearer:
    description: Auth with Bearer
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
