---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/private/get_troubles":
    get:
      summary: Internet Troubles
      tags:
      - Admin
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: string
      - name: size
        in: query
        required: false
        schema:
          type: string
      - name: type
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Get internet troubles
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  page:
                    type: integer
                  size:
                    type: integer
                  total_page:
                    type: integer
                  total_size:
                    type: integer
                  internet_troubles:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        user_id:
                          type: integer
                        trouble:
                          type: string
                        status:
                          type: string
                        category:
                          type: string
                        is_predicted:
                          type: boolean
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        is_read_by_admin:
                          type: string
                          nullable: true
                required:
                - success
                - message
                - page
                - size
                - total_page
                - total_size
                - internet_troubles
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                - success
                - message
  "/api/v1/private/internet_troubles/{id}/edit":
    put:
      summary: Update created internet trouble
      tags:
      - InternetTrouble
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  internet_trouble:
                    type: object
                    properties:
                      trouble:
                        type: string
                        nullable: true
                      status:
                        type: string
                        nullable: true
                      category:
                        type: string
                        nullable: true
                      is_predicted:
                        type: boolean
                required:
                - success
                - message
                - internet_trouble
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: object
                required:
                - success
                - message
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trouble:
                  type: string
                category:
                  type: string
                status:
                  type: string
                is_predicted:
                  type: boolean
  "/api/v1/private/internet_troubles":
    post:
      summary: Create new internet trouble
      tags:
      - InternetTrouble
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  internet_trouble:
                    type: object
                    properties:
                      id:
                        type: integer
                      trouble:
                        type: string
                      status:
                        type: string
                        nullable: true
                      category:
                        type: string
                        nullable: true
                      is_predicted:
                        type: boolean
                    required:
                    - id
                    - trouble
                    - is_predicted
                required:
                - success
                - message
                - internet_trouble
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: object
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trouble:
                  type: string
                category:
                  type: string
                status:
                  type: string
                is_predicted:
                  type: boolean
              required:
              - trouble
    get:
      summary: Get internet troubles
      tags:
      - InternetTrouble
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: string
      - name: size
        in: query
        required: false
        schema:
          type: string
      - name: type
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Get internet troubles
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  page:
                    type: integer
                  size:
                    type: integer
                  total_page:
                    type: integer
                  total_size:
                    type: integer
                  internet_troubles:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        user_id:
                          type: integer
                        trouble:
                          type: string
                        status:
                          type: string
                        category:
                          type: string
                        is_predicted:
                          type: boolean
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        is_read_by_admin:
                          type: string
                          nullable: true
                required:
                - success
                - message
                - page
                - size
                - total_page
                - total_size
                - internet_troubles
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                - success
                - message
  "/api/v1/private/users":
    post:
      summary: Create new user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      created:
                        type: string
                    required:
                    - name
                    - email
                    - created
                required:
                - success
                - message
                - user
        '400':
          description: User did not pass validation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: object
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/api/v1/private/users/login":
    post:
      summary: Authenticate user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: Authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  name:
                    type: string
                  regular_user:
                    type: boolean
                  token:
                    type: string
                required:
                - success
                - message
                - name
                - token
                - regular_user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/internet_troubles":
    post:
      summary: Internet Trouble
      tags:
      - InternetTrouble
      parameters: []
      responses:
        '200':
          description: Show Internet Trouble
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  internet_trouble:
                    type: object
                    properties:
                      id:
                        type: integer
                      trouble:
                        type: string
                      status:
                        type: string
                        nullable: true
                      category:
                        type: string
                        nullable: true
                      is_predicted:
                        type: boolean
                    required:
                    - id
                    - trouble
                    - is_predicted
                required:
                - success
                - message
                - internet_trouble
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                - success
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                trouble_id:
                  type: integer
              required:
              - email
              - trouble_id
securitySchemes:
  Bearer:
    description: Auth with Bearer
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
